[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pda = "BdeucE6HHMSm7LvAgN7ZKCDTJicps7F1n3MGCgR4HxRJ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
