[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "F3hJJ223dGPXzqq4VLiPMNNmXYTomL6T9GdE2hvur8ha"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
